### ISSUE TITLE
To-Do || Upcoming Features

### ISSUE THREAD

**Issue by alisamki** [WatermelonKatanaDevs/WatermelonKatana#6]
# To-Do 

The following list are features, items, and other elements of the website that are going to be added to WatermelonKatana in the future.

## Phase 1 : Prototyping (Complete!)

-   Timeframe: Summer of 2024
    (Done Wed Aug 07 2024 20\:02:38 GMT-0700 (Pacific Daylight Time), Ahead of Deadline!)
-   Completely Private

## Step 1 - Accounts

-   [x] Basic Account/Profile System - DragonFireGames
-   [x] User Settings - DragonFireGames
-   [x] Profile Page - Colack
-   [x] Home Page - Colack & LGM Productions & IMPixel

### Step 2 - Posting Projects

-   [x] Game Embed System - Varrience
-   [x] CDO, Khan, and Scratch support - Varrience & DragonFireGames
-   [x] Publishing Panel - DragonFireGames
-   [x] Post/Forum Viewer - Colack & DragonFireGames & Letti
-   [x] Commenting System - DragonFireGames
-   [x] Favorite System - Colack & DragonFireGames
-   [x] Tag System/Search - Colack & DragonFireGames

### Step 3 - Forums

-   [x] Posting System & Forums - DragonFireGames
-   [x] Upvote System - DragonFireGames
-   [x] Follow Systems - DragonFireGames

### Step 4 - Quick Chat

-   [x] Chat System using discord - DragonFireGames
-   [x] Use account photo/name in quick chat - DragonFireGames

## Phase 2 - Development (ACTIVE)

-   Timeframe: Winter of 2024-2025 (Lets shoot for Thanksgiving??)
-   Limited access Beta

### Step 1 - Administation

-   [ ] Administration Panel
-   [ ] Moderation Panel
-   [ ] Anonymous Mode???
-   [x] Reporting System - DragonFireGames

### Step 2 - More Features

-   [x] Notifications - DragonFireGames & Colack
-   [x] Media Uploading System - DragonFireGames
-   [ ] Dashboard page for users with suggested games based on what they have favorited
-   [x] Better Search for Posts/Users/Games - DragonFireGames
-   [x] Navbar - Colack & DragonFireGames
-   [x] Community Ranking - DragonFireGames
-   [ ] Private Forums, Quick-Chats & Games
-   [x] Featured Games - DragonFireGames
-   [x] Admins / Moderators ability to pin posts - DragonFireGames
-   [ ] Post games directly using GitHub without requiring a static host url to be embedded
-   [x] Flash support???
-   [ ] Profile Badges - Colack
-   [x] Mature game/post rating option - DragonFireGames
-   [x] Hidden games/posts - DragonFireGames
-   [ ] Game Verification
-   [ ] Improve Security (XSS, SQL Injection, etc.) - toodols & DragonFireGames & Letti
-   [x] Email Verification - DragonFireGames
-   [x] Forget and Reset Password using emails - DragonFireGames

### Step 3 - Better UI

-   [ ] Logo
-   [ ] UI Overhaul
    -   [ ] Home Page
    -   [ ] Forum Page - Varrience
    -   [ ] Gallery/Search Page - GxBriel & Varrience
    -   [ ] User Profile Page
    -   [ ] Project Page
    -   [ ] Discussion Page
    -   [ ] User List Page
    -   [ ] Profile Settings Page
    -   [ ] Login Page
    -   [ ] Register Page
    -   [ ] Post Project Page
    -   [ ] Post Discussion Page
    -   [ ] Edit Project Page
    -   [ ] Edit Discussion Page
    -   [ ] Edit Profile Page
    -   [ ] Change Password Page
    -   [ ] Admin Page
    -   [ ] 404 Page
    -   [ ] 403 Page
-   [ ] Dark/Light mode & themes
-   [ ] Markdown Support
-   [ ] Custom Emoji Support
-   [ ] Project css for preview, (background color and text color)
-   [ ] Nameplates?!?!!??!!??!?

## Phase 3 - Deployment

-   Timeframe: Summer of 2025
-   Open Beta

### Step 1 - Add Remaining Features

-   [ ] Save for Later tab
-   [ ] Newsletter + Forgot Password for verified accounts
-   [ ] Community Leaderboards
-   [ ] Improve Performance
-   [ ] Friend activity monitor (what are they doing?)
-   [ ] Live Game Chat???
-   [ ] Remix System (integrated with Github/Free Deployment Software)???
-   [ ] Code editor???
-   [ ] Public Version Management (from Github)
-   [ ] Profile Statuses
-   [ ] Game Jams?

### Step 2 - Final Debugging/Graphics

-   [ ] Fix Remaining Server Issues
-   [ ] Improve Security (XSS, SQL Injection, etc.)
-   [ ] Improve Performance
-   [ ] Finalize GUI/Graphics
-   [ ] Custom Color Stylesheets

## Phase 4 - Production

-   Timeframe: Winter of 2025 onwards
-   Completely Open Public Access

### Step 1 - Maintenence

-   [ ] Bot API
-   [ ] Embed external websites in posts
-   [ ] Bug Fixes + Security + Performance
-   [ ] Establish a healthy moderator community

### Step 2 - Spread Awareness

-   [ ] Spread Awareness for the site (also done during Beta)
-   [ ] Ad-Campaigns across scratch & code.org
-   [ ] Post it everywhere
-   [x] Discord Server
-   [ ] Make it Popular (Honeymoon phase)

### Step 3 - Cash Out

-   [ ] Form a corporation, make a logo, do it properly
-   [ ] The ads must sell that will be your new philosophy
-   [ ] Migrate to paid production environment
-   [ ] Scale Up, Scale up, handle a large userbase
-   [ ] Hire Staff (or rely on volunteer moderation like Reddit)
-   [ ] Page Ads (before games)
-   [ ] Page Ads (during games)
-   [ ] Page Ads (around games)
-   [ ] Excessive Page Ads for Anonymous Users
-   [ ] Ad-free subscription service
-   [ ] Sell Private Account information to China
-   [ ] Sell company to Microsoft for $10,000,000,000

**Comment by Colack** [comment]
working on flash soon
